server: 
  port: 8081

# Database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_registtration
    username: root
    password: Admin1234567@
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
